<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <RootNamespace>Material_Editor</RootNamespace>
    <AssemblyName>bgem</AssemblyName>
    <AssemblyTitle>B.G.E.M.</AssemblyTitle>
    <Product>B.G.E.M.</Product>
    <PackageId>bgem</PackageId>
    <UseWindowsForms>true</UseWindowsForms>
    <StartupObject>Material_Editor.Program</StartupObject>
    <ApplicationIcon>assets\bgem.ico</ApplicationIcon>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Copyright>Copyright © 2015 - 2025</Copyright>
    <Company>Audpocalypse</Company>
    <Authors>Audpocalypse</Authors>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
    <PackageProjectUrl>https://github.com/Audpocalypse/B.G.E.M.</PackageProjectUrl>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MaterialLib.Tests\**" />
    <Compile Remove="MaterialLib\**" />
    <EmbeddedResource Remove="MaterialLib.Tests\**" />
    <EmbeddedResource Remove="MaterialLib\**" />
    <None Remove="MaterialLib.Tests\**" />
    <None Remove="MaterialLib\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\bgem.ico" LogicalName="Material_Editor.assets.bgem.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="MaterialLib\MaterialLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
